'use client';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import Head from 'next/head';
import { Provider } from 'react-redux';
import store from '@/redux/store';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'H.A.M',
//   description: 'Generated by Next.js',
//   icons: {
//     icon: 'https://res.cloudinary.com/dytnpjxrd/image/upload/v1698682275/HAMFOODS/headicon_gd57zk.png',
//     apple: 'https://res.cloudinary.com/dytnpjxrd/image/upload/v1698682275/HAMFOODS/headicon_gd57zk.png',
//   },
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang='en'>
        <Head>
          <title>H.A.M</title>
          <meta name='description' content='Description of your page' />
          <link
            rel='icon'
            href='https://res.cloudinary.com/dytnpjxrd/image/upload/v1698682275/HAMFOODS/headicon_gd57zk.png'
          />
        </Head>
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>
  );
}
